"""user_api_credentials para claves propias del cliente

Revision ID: 8939fe84d4d2
Revises: 2b4dc6ac964b
Create Date: 2026-08-09 14:41:38.994401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8939fe84d4d2'
down_revision: Union[str, None] = '2b4dc6ac964b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_api_credentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('google_places_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('anthropic_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('openai_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_api_credentials')
    # ### end Alembic commands ###
