"""organizaciones y equipos

Revision ID: aaf183612202
Revises: 8939fe84d4d2
Create Date: 2026-08-11 23:30:15.047326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf183612202'
down_revision: Union[str, None] = '8939fe84d4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='organizationrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_membership_org_user')
    )
    op.create_table('organization_invitations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='organizationrole'), nullable=False),
    sa.Column('invited_by_user_id', sa.String(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_invitations_email'), 'organization_invitations', ['email'], unique=False)
    # ### end Alembic commands ###

    # --- Backfill: cada usuario que ya existía antes de esta funcionalidad
    # recibe su propia organización personal, con él mismo como 'owner'.
    # Así el comportamiento no cambia para nadie: cada uno sigue viendo
    # exactamente lo mismo que antes (solo él mismo), hasta que decida
    # invitar a alguien. No se toca la tabla 'businesses' ni ninguna otra
    # tabla de datos existente.
    import uuid
    from datetime import datetime

    conn = op.get_bind()
    users_without_org = conn.execute(sa.text("""
        SELECT u.id, u.email FROM users u
        LEFT JOIN memberships m ON m.user_id = u.id
        WHERE m.id IS NULL
    """)).fetchall()

    now = datetime.utcnow()
    for user_id, email in users_without_org:
        org_id = str(uuid.uuid4())
        conn.execute(
            sa.text("INSERT INTO organizations (id, name, created_at) VALUES (:id, :name, :created_at)"),
            {"id": org_id, "name": f"Organización de {email}", "created_at": now},
        )
        conn.execute(
            sa.text(
                "INSERT INTO memberships (id, organization_id, user_id, role, created_at) "
                "VALUES (:id, :organization_id, :user_id, 'owner', :created_at)"
            ),
            {"id": str(uuid.uuid4()), "organization_id": org_id, "user_id": user_id, "created_at": now},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_invitations_email'), table_name='organization_invitations')
    op.drop_table('organization_invitations')
    op.drop_table('memberships')
    op.drop_table('organizations')
    # ### end Alembic commands ###
