"""baseline: esquema inicial

Revision ID: cc333fa260ae
Revises: 
Create Date: 2026-08-05 08:30:55.840385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc333fa260ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_usage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppression_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppression_entries_value'), 'suppression_entries', ['value'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('email_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prospecting_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('service_offered', sa.Text(), nullable=True),
    sa.Column('ideal_customer', sa.Text(), nullable=True),
    sa.Column('cities', sa.JSON(), nullable=True),
    sa.Column('niches', sa.JSON(), nullable=True),
    sa.Column('positive_signals', sa.JSON(), nullable=True),
    sa.Column('negative_signals', sa.JSON(), nullable=True),
    sa.Column('value_proposition', sa.Text(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('allowed_channels', sa.JSON(), nullable=True),
    sa.Column('scoring_weights', sa.JSON(), nullable=True),
    sa.Column('contact_limits', sa.JSON(), nullable=True),
    sa.Column('consent_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('profile_id', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('niche', sa.String(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('max_results', sa.Integer(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('source_mode', sa.String(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['prospecting_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('businesses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('search_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('phone_intl', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('website_domain', sa.String(), nullable=True),
    sa.Column('google_maps_url', sa.String(), nullable=True),
    sa.Column('place_id', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('opening_hours', sa.JSON(), nullable=True),
    sa.Column('is_open_now', sa.Boolean(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('whatsapp_link', sa.String(), nullable=True),
    sa.Column('whatsapp_status', sa.String(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('crm_stage', sa.Enum('descubierto', 'pendiente_analizar', 'analizado', 'oportunidad_alta', 'pendiente_revisar', 'preparado_contactar', 'contactado', 'respondio', 'interesado', 'reunion_concertada', 'propuesta_enviada', 'negociacion', 'cliente', 'no_interesado', 'seguimiento_futuro', 'perdido', 'excluido', name='leadstage'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', name='uq_business_place_id')
    )
    op.create_index('ix_business_domain', 'businesses', ['website_domain'], unique=False)
    op.create_index(op.f('ix_businesses_place_id'), 'businesses', ['place_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('business_contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('subtype', sa.String(), nullable=True),
    sa.Column('confidence', sa.Enum('verified', 'high', 'medium', 'low', 'not_found', 'not_verified', name='confidencelevel'), nullable=True),
    sa.Column('source', sa.Enum('google_places_api', 'business_website', 'ai_inference', 'manual_entry', 'demo_mock', name='datasourcetype'), nullable=True),
    sa.Column('found_on_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('need_score', sa.Integer(), nullable=True),
    sa.Column('potential_score', sa.Integer(), nullable=True),
    sa.Column('contactability_score', sa.Integer(), nullable=True),
    sa.Column('fit_score', sa.Integer(), nullable=True),
    sa.Column('penalties', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('main_reasons', sa.JSON(), nullable=True),
    sa.Column('risks', sa.JSON(), nullable=True),
    sa.Column('best_offer', sa.String(), nullable=True),
    sa.Column('best_channel', sa.String(), nullable=True),
    sa.Column('score_confidence', sa.Enum('verified', 'high', 'medium', 'low', 'not_found', 'not_verified', name='confidencelevel'), nullable=True),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    op.create_table('message_drafts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('short_version', sa.Text(), nullable=True),
    sa.Column('consultative_version', sa.Text(), nullable=True),
    sa.Column('follow_up', sa.Text(), nullable=True),
    sa.Column('objection_response', sa.Text(), nullable=True),
    sa.Column('used_evidence', sa.JSON(), nullable=True),
    sa.Column('ai_provider', sa.String(), nullable=True),
    sa.Column('ai_model', sa.String(), nullable=True),
    sa.Column('confidence', sa.Enum('verified', 'high', 'medium', 'low', 'not_found', 'not_verified', name='confidencelevel'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('gmail_draft_id', sa.String(), nullable=True),
    sa.Column('gmail_message_id', sa.String(), nullable=True),
    sa.Column('gmail_thread_id', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('confidence', sa.Enum('verified', 'high', 'medium', 'low', 'not_found', 'not_verified', name='confidencelevel'), nullable=True),
    sa.Column('estimated_impact', sa.String(), nullable=True),
    sa.Column('estimated_effort', sa.String(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('sales_angle', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('website_audits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('reachable', sa.Boolean(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('https', sa.Boolean(), nullable=True),
    sa.Column('is_parked_or_placeholder', sa.Boolean(), nullable=True),
    sa.Column('mobile_friendly', sa.Boolean(), nullable=True),
    sa.Column('has_viewport_meta', sa.Boolean(), nullable=True),
    sa.Column('performance_score_mobile', sa.Integer(), nullable=True),
    sa.Column('performance_score_desktop', sa.Integer(), nullable=True),
    sa.Column('load_time_ms', sa.Integer(), nullable=True),
    sa.Column('has_cta', sa.Boolean(), nullable=True),
    sa.Column('has_contact_form', sa.Boolean(), nullable=True),
    sa.Column('has_booking', sa.Boolean(), nullable=True),
    sa.Column('has_whatsapp_button', sa.Boolean(), nullable=True),
    sa.Column('has_call_button', sa.Boolean(), nullable=True),
    sa.Column('has_title', sa.Boolean(), nullable=True),
    sa.Column('has_meta_description', sa.Boolean(), nullable=True),
    sa.Column('has_h1', sa.Boolean(), nullable=True),
    sa.Column('has_structured_data', sa.Boolean(), nullable=True),
    sa.Column('has_sitemap', sa.Boolean(), nullable=True),
    sa.Column('has_privacy_policy', sa.Boolean(), nullable=True),
    sa.Column('has_cookie_banner', sa.Boolean(), nullable=True),
    sa.Column('visual_assessment', sa.JSON(), nullable=True),
    sa.Column('source_mode', sa.String(), nullable=True),
    sa.Column('audited_at', sa.DateTime(), nullable=True),
    sa.Column('raw_findings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('website_audits')
    op.drop_table('tasks')
    op.drop_table('opportunities')
    op.drop_table('message_drafts')
    op.drop_table('lead_scores')
    op.drop_table('business_contacts')
    op.drop_table('activities')
    op.drop_index(op.f('ix_businesses_place_id'), table_name='businesses')
    op.drop_index('ix_business_domain', table_name='businesses')
    op.drop_table('businesses')
    op.drop_table('searches')
    op.drop_table('prospecting_profiles')
    op.drop_table('email_connections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppression_entries_value'), table_name='suppression_entries')
    op.drop_table('suppression_entries')
    op.drop_table('provider_usage')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
